version: '3'

interval: 100ms

tasks:
    build:
        sources:
            - '**/*.odin'
        cmds:
            - odin build .
            - echo "Done building."

    build-prod:
        sources:
            - '**/*.odin'
        cmds:
            - odin build . -o:aggressive
            - echo "Done building."
